---
s3_sync_bucket: kubelini
cluster_ip_range: 10.32.0.0/16
cluster_ip_range_first_ip: 10.32.0.1 #needed for certificate
cluster_dns_address: 10.32.0.10
#this setting controls the ip range for pods:
cluster_cidr: 10.200.0.0/16

cluster_domain: cluster.local
#Set this if you have a LB in front of your controllers!
#kubernetes_cluster_address: 10.245.22.137

weavenet_allocation_cidr: 10.200.0.0/16

#if you set this var, fill it with users that will be added to "static" users:
additional_kubernetes_static_users:
  - user: deploy
    password: whatUp
    uid: '180'
    group: 'system:masters'
  - user: admin
    password: DoIt
    uid: '173'
    group: 'system:masters'