---
kubernetes_version: 1.9.0

s3_sync_bucket: kubelinidev
cluster_ip_range: 10.32.0.0/16
cluster_ip_range_first_ip: 10.32.0.1 #needed for certificate
cluster_dns_address: 10.32.0.10

#this setting controls the ip range for pods. 
#Usually this should line up with the weave/flannel cidr defined bellow.
cluster_cidr: 10.200.0.0/16

cluster_domain: cluster.local

#Set this if you have a LB in front of your controllers!
#If not, use the first master node in your inventory
kubernetes_cluster_address: 10.245.22.31

#Don't change these networking variables after your control plane nodes (masters) are deployed.
networking_stack: weavenet # set to either weavenet or flannel. 
weavenet_allocation_cidr: 10.200.0.0/16 #needed if networking_stack is set to weavenet
flannel_allocation_cidr:  10.200.0.0/16 #needed if networking_stack is set to flannel

#if you set this var, fill it with users that will be added to "static" users:
additional_kubernetes_static_users:
  - user: deploy
    password: whatUp
    uid: '180'
    group: 'system:masters'
  - user: admin
    password: DoIt
    uid: '173'
    group: 'system:masters'