- name: create etcd folders
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
  - /etc/etcd
  - /opt/kubelini/etcd
  - /var/lib/etcd

- name: Download etcd
  get_url:
    url: https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    dest: /opt/kubelini/etcd-v{{ etcd_version }}-linux-amd64.tar.gz

- name: unpack etcd
  unarchive:
    src: /opt/kubelini/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    dest: /opt/kubelini/etcd
    remote_src: True

- name: Copy etcd to bin
  copy:
    src: "/opt/kubelini/etcd/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    remote_src: yes
    mode: a+x
  with_items:
  - etcd
  - etcdctl

- name: get group ip addresses
  set_fact:
    etc_cluster_controller_str: "{% for h in groups['kubernetes_master'] %}{{ hostvars[h]['inventory_hostname'] }}=https://{{ hostvars[h]['ansible_default_ipv4']['address'] }}:2380{% if not loop.last %},{% endif %}{% endfor %}"

- name: template etcd service definition
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify: reload etcd service

- name: flush handlers
  meta: flush_handlers

