#This playbook configures a node. It's written to be independent so you can run it against a single node with the --limit parameter
---
#Download required binaries
- hosts:
  - kubernetes_worker
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles:
  - kubelini-common

#Generate the node-specific certificate request
- hosts:
  - kubernetes_worker
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles: 
  - kubelini-worker-pki

#Download the CA file(s) from S3, and use it to request/generate required certificates
- hosts:
  - kubernetes_worker
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles: 
  - kubelini-worker-download-stuff
  - kubelini-ca

#Configure kubelet, docker and related things
- hosts:
  - kubernetes_worker
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles: 
  - kubelini-worker-kubelet

