---
- hosts:
  - kubernetes_master
  - kubernetes_worker
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles:
  - kubelini-common

- hosts:
  - kubernetes_master
  - kubernetes_worker
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles: 
  - kubelini-worker-pki

- hosts:
  - kubernetes_master[0]
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles:
  - kubelini-ca

- hosts:
  - kubernetes_master
  - kubernetes_worker
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles: 
  - kubelini-worker-download-stuff

- hosts:
  - kubernetes_master
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles: 
  - kubelini-etcd

- hosts:
  - kubernetes_master
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles: 
  - kubelini-clustercontroller

- hosts:
  - kubernetes_worker
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles: 
  - kubelini-worker-kubelet

- hosts:
  - kubernetes_master[0]
  become: yes
  vars_files:
    - secrets/secrets.yml
  roles:
  - kubelini-addons