- name: reload kube-apiserver
  systemd:
    enabled: yes
    state: restarted
    daemon_reload: yes
    name: kube-apiserver

- name: reload kube-controller-manager
  systemd:
    enabled: yes
    state: restarted
    daemon_reload: yes
    name: kube-controller-manager

- name: reload kube-scheduler
  systemd:
    enabled: yes
    state: restarted
    daemon_reload: yes
    name: kube-scheduler