- name: create folder for deployments
  file:
    dest: /opt/kubelini/deployments
    state: directory

- name: template weave deployment
  template:
    src: weavenet-config.yml.j2
    dest: /opt/kubelini/deployments/weavenet-config.yml
  when: networking_stack == 'weavenet'

- name: template flannel deployment
  template:
    src: flannel-config.yml.j2
    dest: /opt/kubelini/deployments/flannel-config.yml
  when: networking_stack == 'flannel'

- name: template dns deployment
  template:
    src: dns-deployment.yml.j2
    dest: /opt/kubelini/deployments/dns-deployment.yml

- name: template kube-proxy deployment
  template:
    src: node-proxy.yml
    dest: /opt/kubelini/deployments/node-proxy.yml

- name: Apply weave deployment
  shell: kubectl apply -f /opt/kubelini/deployments/weavenet-config.yml
  when: networking_stack == 'weavenet'

- name: Apply flannel deployment
  shell: kubectl apply -f /opt/kubelini/deployments/flannel-config.yml
  when: networking_stack == 'flannel'

- name: Apply kube-proxy deployment
  shell: kubectl apply -f /opt/kubelini/deployments/node-proxy.yml

- name: Apply kubedns deployment
  shell: kubectl apply -f /opt/kubelini/deployments/dns-deployment.yml

- name: Apply metrics-server
  when: kubelini_addons_install_metrics_server | bool
  block:
  - name: Template metrics-server manifests
    template:
      src: "{{ item }}"
      dest: "/opt/kubelini/deployments/{{ item }}"
    with_items:
    - metrics_server_auth_delegator.yml
    - metrics_server_auth_reader.yml
    - metrics_server_resource_reader.yml
    - metrics_server_deployment.yml
    - metrics_server_service.yml
    - metrics_server_apiservice.yml
  - name: apply metrics-server
    shell: "kubectl apply -f  /opt/kubelini/deployments/{{ item }}"
    with_items:
    - metrics_server_auth_delegator.yml
    - metrics_server_auth_reader.yml
    - metrics_server_resource_reader.yml
    - metrics_server_deployment.yml
    - metrics_server_service.yml
    - metrics_server_apiservice.yml

